name: Build and deploy code

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v4
      - name: install python
        uses: actions/etup-python@v2
        with:
          python-version: "3.9"
 